import os
from pyrogram import Client

API_ID = int(os.environ.get("API_ID", "34422904"))
API_HASH = os.environ.get("API_HASH", "7e0002469784f47fc08a6b3d93d7ebed")
BOT_TOKEN = os.environ.get("BOT_TOKEN", "8943498016:AAGetKpSyQcSvg8ypR9F2gbHK0AKzNZVqrw")

bot = Client(
    '『 𝐓𝐇𝐎𝐑 』™',
    bot_token=BOT_TOKEN,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    api_id=API_ID,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    api_hash=API_HASH
)

BotVersion = "49.0.01"
my_vercel_api = "https://thor-x1-api.vercel.app"
my_hrk_api = "https://thor-x1-api.vercel.app"
my_auth_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjIyMzMzNzE4IiwiZXhwIjoxNzkwMDYyNDcyfQ.BXic2mI9w3SJKTaR02qTb4sOGo0raLVm1rknuq0qqo8"
owner_id = [5349573682]

FORCE_JOIN_CHANNEL = -1004213211355
log_channel = -1004213211355
LogDumpGrp = -1004213211355
ext_logs = -1004213211355
subscription_log = -1004213211355

zipAPI = os.environ.get("ZipAPI", "https://romeo-zip.dev-boi.xyz")
zipToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjYyMjMzMzcxOCIsInRnX3VzZXJuYW1lIjoibWVnYXRvbiJ9.DaAiOsFR32EvsLcCI2o_wuxMyRLqKSLT9wFRdqpjNio"
