import os
from pyrogram import Client

API_ID = int(os.environ.get("API_ID", "22370234"))
API_HASH = os.environ.get("API_HASH", "706badded011715ae115e5ab3bf83f87")
BOT_TOKEN = os.environ.get("BOT_TOKEN", "")

bot = Client(
    '『 𝐓𝐇𝐎𝐑 』™',
    bot_token=BOT_TOKEN,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    api_id=API_ID,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    api_hash=API_HASH
)

BotVersion = "49.0.01"
my_vercel_api = "https://thor-x1-api.vercel.app"
my_hrk_api = "https://thor-x1-api.vercel.app"
my_auth_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjIyMzMzNzE4IiwiZXhwIjoxNzkwMDYyNDcyfQ.BXic2mI9w3SJKTaR02qTb4sOGo0raLVm1rknuq0qqo8"
owner_id = [8042993273, 7974818772,1193248592]

FORCE_JOIN_CHANNEL = -1002889270364
log_channel = -1002948789057
LogDumpGrp = -1003188877042
ext_logs = -1002914042438
subscription_log = -1002941560431

zipAPI = os.environ.get("ZipAPI", "https://romeo-zip.dev-boi.xyz")
zipToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjYyMjMzMzcxOCIsInRnX3VzZXJuYW1lIjoibWVnYXRvbiJ9.DaAiOsFR32EvsLcCI2o_wuxMyRLqKSLT9wFRdqpjNio"
