def get_caption_style(caption_style, count, name1, res, b_name, EX, CR, url):                  
  captions = {}
  if caption_style == "style1":
          captions["cc"] = f'**┏━━━━━━━━━ ✦ File Info ✦ ━━━━━━━━━┓**\n**┃ 📋 Title :** `{name1}`\n**┃ 🎥 Extension :** {EX}.mkv\n**┃ 📏 Resolution :** [{res}]\n**┗━━━━━━━━━━ ✦ {str(count).zfill(3)} ✦ ━━━━━━━━━━┛**\n\n<blockquote>🧾 **Course Name :** {b_name}</blockquote>\n\n💻 **Extracted By :** {CR}'
          captions["ccstream"] = f'**┏━━━━━━━━━ ✦ File Info ✦ ━━━━━━━━━┓**\n**┃ 📋 Title :** `{name1}`\n**┃ 🎥 Extension :** {EX}.mkv\n**┃ 📏 Resolution :** [{res}]\n**┗━━━━━━━━━━ ✦ {str(count).zfill(3)} ✦ ━━━━━━━━━━┛**\n\n<blockquote>🧾 **Course Name :** {b_name}</blockquote>\n\n💻 **Extracted By :** {CR}\n\n<blockquote>**[✨ Stream it for the best Viewing Experience!]({url})**</blockquote>'
          captions["cctest"] = f'**┏━━━━━━━━━ ✦ File Info ✦ ━━━━━━━━━┓**\n**┃ 📋 Title :** `{name1}`\n**┃ 🎥 Extension :** {EX}.mkv\n**┃ 📏 Resolution :** [{res}]\n**┗━━━━━━━━━━ ✦ {str(count).zfill(3)} ✦ ━━━━━━━━━━┛**\n\n<blockquote>🧾 **Course Name :** {b_name}</blockquote>\n\n💻 **Extracted By :** {CR}\n\n<blockquote>✨ Press the <b>Start Button</b> to Start the Test!</blockquote>'
          captions["ccyt"] = f'**┏━━━━━━━━━ ✦ File Info ✦ ━━━━━━━━━┓**\n**┃ 📋 Title :** `{name1}`\n**┃ 🎥 Extension :** {EX}.mkv\n**┃ 📏 Resolution :** [{res}]\n**┗━━━━━━━━━━ ✦ {str(count).zfill(3)} ✦ ━━━━━━━━━━┛**\n\n<blockquote>🧾 **Course Name :** {b_name}</blockquote>\n\n💻 **Extracted By :** {CR}\n\n<blockquote>**[🌟 It seems that this Video can be best enjoyed on YouTube.]({url})**</blockquote>'
          captions["cc1"] = f'**┏━━━━━━━━━ ✦ File Info ✦ ━━━━━━━━━┓**\n**┃ 📋 Title :** `{name1}`\n**┃ 🎥 Extension :** {EX}.pdf\n**┗━━━━━━━━━━ ✦ {str(count).zfill(3)} ✦ ━━━━━━━━━━┛**\n\n<blockquote>🧾 **Course Name :** {b_name}</blockquote>\n\n💻 **Extracted By :** {CR}'
          captions["cchtml"] = f'**┏━━━━━━━━━ ✦ File Info ✦ ━━━━━━━━━┓**\n**┃ 📋 Title :** `{name1}`\n**┃ 🎥 Extension :** {EX}.html\n**┗━━━━━━━━━━ ✦ {str(count).zfill(3)} ✦ ━━━━━━━━━━┛**\n\n<blockquote>🧾 **Course Name :** {b_name}</blockquote>\n\n💻 **Extracted By :** {CR}'
  elif caption_style == "style2":
          captions["cc"] = f'❖────────── **{str(count).zfill(3)}** ──────────❖\n\n📋 **Title :** `{name1}`\n🎞️ **Extension :** {EX}.mkv\n📏 **Resolution :** [{res}]\n\n<blockquote>📘 **Course Name :** {b_name}</blockquote>\n\n❖──────── **{CR}** ────────❖'
          captions["ccstream"] = f'❖────────── **{str(count).zfill(3)}** ──────────❖\n\n📋 **Title :** `{name1}`\n🎞️ **Extension :** {EX}.mkv\n📏 **Resolution :** [{res}]\n\n<blockquote>📘 **Course Name :** {b_name}</blockquote>\n\n❖──────── **{CR}** ────────❖\n\n<blockquote>**[✨ Stream it for the best Viewing Experience!]({url})**</blockquote>'
          captions["cctest"] = f'❖────────── **{str(count).zfill(3)}** ──────────❖\n\n📋 **Title :** `{name1}`\n🎞️ **Extension :** {EX}.mkv\n📏 **Resolution :** [{res}]\n\n<blockquote>📚 <b>Course Name :</b> {b_name}</blockquote>\n\n❖──────── **{CR}** ────────❖\n\n<blockquote>✨ Press the <b>Start Button</b> to Start the Test!</blockquote>'
          captions["ccyt"] = f'❖────────── **{str(count).zfill(3)}** ──────────❖\n\n📋 **Title :** `{name1}`\n🎞️ **Extension :** {EX}.mkv\n📏 **Resolution :** [{res}]\n\n<blockquote>📘 **Course Name :** {b_name}</blockquote>\n\n❖──────── **{CR}** ────────❖\n\n<blockquote>**[🌟 It seems that this Video can be best enjoyed on YouTube.]({url})**</blockquote>'
          captions["cc1"] = f'❖────────── **{str(count).zfill(3)}** ──────────❖\n\n📋 **Title :** `{name1}`\n🎞️ **Extension :** {EX}.pdf\n\n<blockquote>📘 **Course Name :** {b_name}</blockquote>\n\n❖──────── **{CR}** ────────❖'
          captions["cchtml"] = f'❖────────── **{str(count).zfill(3)}** ──────────❖\n\n📋 **Title :** `{name1}`\n🎞️ **Extension :** {EX}.html\n\n<blockquote>📘 **Course Name :** {b_name}</blockquote>\n\n❖──────── **{CR}** ────────❖'
  elif caption_style == "style3":
          captions["cc"] = f'**────────── ✧ {str(count).zfill(3)} ✧ ──────────**\n📝 **Title :**\n  **➜** `{name1}`\n🎞️ **File Info :**\n  **• Extension :** {EX}.mkv\n  **• Resolution :** [{res}]\n\n📘 **Course Name :**\n  **➜** {b_name}\n\n⭐ **Extracted By :** {CR}'
          captions["ccstream"] = f'**────────── ✧ {str(count).zfill(3)} ✧ ──────────**\n📝 **Title :**\n  **➜** `{name1}`\n🎞️ **File Info :**\n  **• Extension :** {EX}.mkv\n  **• Resolution :** [{res}]\n\n📘 **Course Name :**\n  **➜** {b_name}\n\n⭐ **Extracted By :** {CR}\n\n<blockquote>**[✨ Stream it for the best Viewing Experience!]({url})**</blockquote>'
          captions["cctest"] = f'**────────── ✧ {str(count).zfill(3)} ✧ ──────────**\n📝 **Title :**\n  **➜** `{name1}`\n🎞️ **File Info :**\n  **• Extension :** {EX}.mkv\n  **• Resolution :** [{res}]\n\n📘 **Course Name :**\n  **➜** {b_name}\n\n⭐ **Extracted By :** {CR}\n\n<blockquote>✨ Press the <b>Start Button</b> to Start the Test!</blockquote>'
          captions["ccyt"] = f'**────────── ✧ {str(count).zfill(3)} ✧ ──────────**\n📝 **Title :**\n  **➜** `{name1}`\n🎞️ **File Info :**\n  **• Extension :** {EX}.mkv\n  **• Resolution :** [{res}]\n\n📘 **Course Name :**\n  **➜** {b_name}\n\n⭐ **Extracted By :** {CR}\n\n<blockquote>**[🌟 It seems that this Video can be best enjoyed on YouTube.]({url})**</blockquote>'
          captions["cc1"] = f'**────────── ✧ {str(count).zfill(3)} ✧ ──────────**\n📝 **Title :**\n  **➜** `{name1}`\n🎞️ **File Info :**\n  **• Extension :** {EX}.pdf\n\n📘 **Course Name :**\n  **➜** {b_name}\n\n⭐ **Extracted By :** {CR}'
          captions["cchtml"] = f'**────────── ✧ {str(count).zfill(3)} ✧ ──────────**\n📝 **Title :**\n  **➜** `{name1}`\n🎞️ **File Info :**\n  **• Extension :** {EX}.html\n\n📘 **Course Name :**\n  **➜** {b_name}\n\n⭐ **Extracted By :** {CR}'
  elif caption_style == "style4":
          captions["cc"] = f'——— ✦ {str(count).zfill(3)} ✦ ———\n\n**[📽] Title :** {name1} [{res}] {EX}.mkv\n\n<blockquote>📚 Batch Name : {b_name}</blockquote>\n\n🌟 **Extracted By :** {CR}'
          captions["ccstream"] = f'——— ✦ {str(count).zfill(3)} ✦ ———\n\n**[📽] Title :** {name1} [{res}] {EX}.mkv\n\n<blockquote>📚 Batch Name : {b_name}</blockquote>\n\n🌟 **Extracted By :** {CR}\n\n<blockquote>**[✨ Stream it for the best Viewing Experience!]({url})**</blockquote>'
          captions["cctest"] = f'——— ✦ {str(count).zfill(3)} ✦ ———\n\n**[📽] Title :** {name1} [{res}] {EX}.mkv\n\n<blockquote>📚 Batch Name : {b_name}</blockquote>\n\n🌟 **Extracted By :** {CR}\n\n<blockquote>✨ Press the <b>Start Button</b> to Start the Test!</blockquote>'
          captions["ccyt"] = f'——— ✦ {str(count).zfill(3)} ✦ ———\n\n**[📽] Title :** {name1} [{res}] {EX}.mkv\n\n<blockquote>📚 Batch Name : {b_name}</blockquote>\n\n🌟 **Extracted By :** {CR}\n\n<blockquote>**[🌟 It seems that this Video can be best enjoyed on YouTube.]({url})**</blockquote>'
          captions["cc1"] = f'——— ✦ {str(count).zfill(3)} ✦ ———\n\n**[📁] Title :** {name1} {EX}.pdf\n\n<blockquote>📚 Batch Name : {b_name}</blockquote>\n\n🌟 **Extracted By :** {CR}'
          captions["cchtml"] = f'——— ✦ {str(count).zfill(3)} ✦ ———\n\n**[📁] Title :** {name1} {EX}.html\n\n<blockquote>📚 Batch Name : {b_name}</blockquote>\n\n🌟 **Extracted By :** {CR}'
  else:
          captions["cc"] = f'**——— ✦ {str(count).zfill(3)} ✦ ———**\n\n**🎞️ Title :** `{name1}`\n├── **Extention** : {EX}.mkv\n├── **Resolution** : [{res}]\n\n<blockquote>**📚 Course :** {b_name}</blockquote>\n\n**🌟 Extracted By : {CR}**'
          captions["ccstream"] = f'**——— ✦ {str(count).zfill(3)} ✦ ———**\n\n**🎞️ Title :** `{name1}`\n├── **Extention** : {EX}.mkv\n├── **Resolution** : [{res}]\n\n<blockquote>**📚 Course :** {b_name}</blockquote>\n\n**🌟 Extracted By : {CR}**\n\n<blockquote>**[✨ Stream it for the best Viewing Experience!]({url})**</blockquote>'
          captions["cctest"] = f'**——— ✦ {str(count).zfill(3)} ✦ ———**\n\n**🎞️ Title :** `{name1}`\n├── **Extention** : {EX}.mkv\n├── **Resolution** : [{res}]\n\n<blockquote>**📚 Course :** {b_name}</blockquote>\n\n**🌟 Extracted By : {CR}**\n\n<blockquote>✨ Press the <b>Start Button</b> to Start the Test!</blockquote>'
          captions["ccyt"] = f'**——— ✦ {str(count).zfill(3)} ✦ ———**\n\n**🎞️ Title :** `{name1}`\n├── **Extention** : {EX}.mkv\n├── **Resolution** : [{res}]\n\n<blockquote>**📚 Course :** {b_name}</blockquote>\n\n**🌟 Extracted By : {CR}**\n\n<blockquote>**[🌟 It seems that this Video can be best enjoyed on YouTube.]({url})**</blockquote>'
          captions["cc1"] = f'**——— ✦ {str(count).zfill(3)} ✦ ———**\n\n**📁 Title :** `{name1}`\n├── **Extention** : {EX}.pdf \n\n<blockquote>**📚 Course :** {b_name}</blockquote>\n\n**🌟 Extracted By : {CR}**'
          captions["cchtml"] = f'**——— ✦ {str(count).zfill(3)} ✦ ———**\n\n**📁 Title :** `{name1}`\n├── **Extention** : {EX}.html \n\n<blockquote>**📚 Course :** {b_name}</blockquote>\n\n**🌟 Extracted By : {CR}**'
        
  return captions 

def get_t_caption_styles(caption_style, count, name1, t_name, v_name, res, b_name, EX, CR, url):
        t_captions = {}

        if caption_style == "style1":
              t_captions["cc"] = f'**┏━━━━━━━━━ ✦ File Info ✦ ━━━━━━━━━┓**\n**⋅ ─  🔖 {t_name}  ─ ⋅**\n**┃ 📋 Title :** `{v_name}`\n**┃ 🎥 Extension :** {EX}.mkv\n**┃ 📏 Resolution :** [{res}]\n**┗━━━━━━━━━━ ✦ {str(count).zfill(3)} ✦ ━━━━━━━━━━┛**\n\n<blockquote>🧾 **Course Name :** {b_name}</blockquote>\n\n💻 **Extracted By :** {CR}'
              t_captions["ccstream"] = f'**┏━━━━━━━━━ ✦ File Info ✦ ━━━━━━━━━┓**\n**⋅ ─  🔖 {t_name}  ─ ⋅**\n**┃ 📋 Title :** `{v_name}`\n**┃ 🎥 Extension :** {EX}.mkv\n**┃ 📏 Resolution :** [{res}]\n**┗━━━━━━━━━━ ✦ {str(count).zfill(3)} ✦ ━━━━━━━━━━┛**\n\n<blockquote>🧾 **Course Name :** {b_name}</blockquote>\n\n💻 **Extracted By :** {CR}\n\n<blockquote>**[✨ Stream it for the best Viewing Experience!]({url})**</blockquote>'
              t_captions["cctest"] = f'**┏━━━━━━━━━ ✦ File Info ✦ ━━━━━━━━━┓**\n**⋅ ─  🔖 {t_name}  ─ ⋅**\n**┃ 📋 Title :** `{v_name}`\n**┃ 🎥 Extension :** {EX}.mkv\n**┃ 📏 Resolution :** [{res}]\n**┗━━━━━━━━━━ ✦ {str(count).zfill(3)} ✦ ━━━━━━━━━━┛**\n\n<blockquote>🧾 **Course Name :** {b_name}</blockquote>\n\n💻 **Extracted By :** {CR}\n\n<blockquote>✨ Press the <b>Start Button</b> to Start the Test!</blockquote>'
              t_captions["ccyt"] = f'**┏━━━━━━━━━ ✦ File Info ✦ ━━━━━━━━━┓**\n**⋅ ─  🔖 {t_name}  ─ ⋅**\n**┃ 📋 Title :** `{v_name}`\n**┃ 🎥 Extension :** {EX}.mkv\n**┃ 📏 Resolution :** [{res}]\n**┗━━━━━━━━━━ ✦ {str(count).zfill(3)} ✦ ━━━━━━━━━━┛**\n\n<blockquote>🧾 **Course Name :** {b_name}</blockquote>\n\n💻 **Extracted By :** {CR}\n\n<blockquote>**[🌟 It seems that this Video can be best enjoyed on YouTube.]({url})**</blockquote>'
              t_captions["cc1"] = f'**┏━━━━━━━━━ ✦ File Info ✦ ━━━━━━━━━┓**\n**⋅ ─  🔖 {t_name}  ─ ⋅**\n**┃ 📋 Title :** `{v_name}`\n**┃ 🎥 Extension :** {EX}.pdf\n**┗━━━━━━━━━━ ✦ {str(count).zfill(3)} ✦ ━━━━━━━━━━┛**\n\n<blockquote>🧾 **Course Name :** {b_name}</blockquote>\n\n💻 **Extracted By :** {CR}'
              t_captions["cchtml"] = f'**┏━━━━━━━━━ ✦ File Info ✦ ━━━━━━━━━┓**\n**⋅ ─  🔖 {t_name}  ─ ⋅**\n**┃ 📋 Title :** `{v_name}`\n**┃ 🎥 Extension :** {EX}.html\n**┗━━━━━━━━━━ ✦ {str(count).zfill(3)} ✦ ━━━━━━━━━━┛**\n\n<blockquote>🧾 **Course Name :** {b_name}</blockquote>\n\n💻 **Extracted By :** {CR}'
        elif caption_style == "style2":
              t_captions["cc"] = f'❖────────── **{str(count).zfill(3)}** ──────────❖\n\n📋 **Title :** `{v_name}`\n🎞️ **Extension :** {EX}.mkv\n📏 **Resolution :** [{res}]\n\n<blockquote>📒 <b>Topic Name :</b> {t_name}\n📚 <b>Course Name :</b> {b_name}</blockquote>\n\n❖─────── **{CR}** ───────❖'
              t_captions["ccstream"] = f'❖────────── **{str(count).zfill(3)}** ──────────❖\n\n🌐 **Title :** `{v_name}`\n🎞️ **Extension :** {EX}.mkv\n📏 **Resolution :** [{res}]\n\n<blockquote>📒 <b>Topic Name :</b> {t_name}\n📚 <b>Course Name :</b> {b_name}</blockquote>\n\n❖──────── **{CR}** ────────❖\n\n<blockquote>**[✨ Stream it for the best Viewing Experience!]({url})**</blockquote>'
              t_captions["cctest"] = f'❖────────── **{str(count).zfill(3)}** ──────────❖\n\n🌐 **Title :** `{v_name}`\n🎞️ **Extension :** {EX}.mkv\n📏 **Resolution :** [{res}]\n\n<blockquote>📒 <b>Topic Name :</b> {t_name}\n📚 <b>Course Name :</b> {b_name}</blockquote>\n\n❖──────── **{CR}** ────────❖\n\n<blockquote>✨ Press the <b>Start Button</b> to Start the Test!</blockquote>'
              t_captions["ccyt"] = f'❖────────── **{str(count).zfill(3)}** ──────────❖\n\n📋 **Title :** `{v_name}`\n🎞️ **Extension :** {EX}.mkv\n📏 **Resolution :** [{res}]\n\n<blockquote>📒 <b>Topic Name :</b> {t_name}\n📚 <b>Course Name :</b> {b_name}</blockquote>\n\n❖──────── **{CR}** ────────❖\n\n<blockquote>**[🌟 It seems that this Video can be best enjoyed on YouTube or Player.]({url})**</blockquote>'
              t_captions["cc1"] = f'❖────────── **{str(count).zfill(3)}** ──────────❖\n\n📋 **Title :** `{v_name}`\n🎞️ **Extension :** {EX}.pdf\n\n<blockquote>📒 <b>Topic Name :</b> {t_name}\n📚 <b>Course Name :</b> {b_name}</blockquote>\n\n❖──────── **{CR}** ────────❖'
              t_captions["cchtml"] = f'❖────────── **{str(count).zfill(3)}** ──────────❖\n\n🌐 **Title :** `{v_name}`\n🎞️ **Extension :** {EX}.html\n\n<blockquote>📒 <b>Topic Name :</b> {t_name}\n📚 <b>Course Name :</b> {b_name}</blockquote>\n\n❖──────── **{CR}** ────────❖'
        elif caption_style == "style3":
              t_captions["cc"] = f'**────────── ✧ {str(count).zfill(3)} ✧ ──────────**\n<blockquote>**⋅ ─  🔖 {t_name}  ─ ⋅**</blockquote>\n\n📝 **Title :**\n  **➜** `{v_name}`\n🎞️ **File Info :**\n  **• Extension :** {EX}.mkv\n  **• Resolution :** [{res}]\n\n📘 **Course Name :**\n  **➜** {b_name}\n\n⭐ **Extracted By :** {CR}'
              t_captions["ccstream"] = f'**────────── ✧ {str(count).zfill(3)} ✧ ──────────**\n<blockquote>**⋅ ─  🔖 {t_name}  ─ ⋅**</blockquote>\n\n📝 **Title :**\n  **➜** `{v_name}`\n🎞️ **File Info :**\n  **• Extension :** {EX}.mkv\n  **• Resolution :** [{res}]\n\n📘 **Course Name :**\n  **➜** {b_name}\n\n⭐ **Extracted By :** {CR}\n\n<blockquote>**[✨ Stream it for the best Viewing Experience!]({url})**</blockquote>'
              t_captions["cctest"] = f'**────────── ✧ {str(count).zfill(3)} ✧ ──────────**\n<blockquote>**⋅ ─  🔖 {t_name}  ─ ⋅**</blockquote>\n\n📝 **Title :**\n  **➜** `{v_name}`\n🎞️ **File Info :**\n  **• Extension :** {EX}.mkv\n  **• Resolution :** [{res}]\n\n📘 **Course Name :**\n  **➜** {b_name}\n\n⭐ **Extracted By :** {CR}\n\n<blockquote>✨ Press the <b>Start Button</b> to Start the Test!</blockquote>'
              t_captions["ccyt"] = f'**────────── ✧ {str(count).zfill(3)} ✧ ──────────**\n<blockquote>**⋅ ─  🔖 {t_name}  ─ ⋅**</blockquote>\n\n📝 **Title :**\n  **➜** `{v_name}`\n🎞️ **File Info :**\n  **• Extension :** {EX}.mkv\n  **• Resolution :** [{res}]\n\n📘 **Course Name :**\n  **➜** {b_name}\n\n⭐ **Extracted By :** {CR}\n\n<blockquote>**[🌟 It seems that this Video can be best enjoyed on YouTube.]({url})**</blockquote>'
              t_captions["cc1"] = f'**────────── ✧ {str(count).zfill(3)} ✧ ──────────**\n<blockquote>**⋅ ─  🔖 {t_name}  ─ ⋅**</blockquote>\n\n📝 **Title :**\n  **➜** `{v_name}`\n🎞️ **File Info :**\n  **• Extension :** {EX}.pdf\n\n📘 **Course Name :**\n  **➜** {b_name}\n\n⭐ **Extracted By :** {CR}'
              t_captions["cchtml"] = f'**────────── ✧ {str(count).zfill(3)} ✧ ──────────**\n<blockquote>**⋅ ─  🔖 {t_name}  ─ ⋅**</blockquote>\n\n📝 **Title :**\n  **➜** `{v_name}`\n🎞️ **File Info :**\n  **• Extension :** {EX}.html\n\n📘 **Course Name :**\n  **➜** {b_name}\n\n⭐ **Extracted By :** {CR}'
        elif caption_style == "style4":
              t_captions["cc"] = f'——— ✦ {str(count).zfill(3)} ✦ ———\n\n<blockquote>**⋅ ─  🔖 {t_name}  ─ ⋅**</blockquote>\n\n**[📽] Title :** {v_name} [{res}] {EX}.mkv\n\n<blockquote>📚 Batch Name : {b_name}</blockquote>\n\n🌟 **Extracted By :** {CR}'
              t_captions["ccstream"] = f'——— ✦ {str(count).zfill(3)} ✦ ———\n\n<blockquote>**⋅ ─  🔖 {t_name}  ─ ⋅**</blockquote>\n\n**[📽] Title :** {v_name} [{res}] {EX}.mkv\n\n<blockquote>📚 Batch Name : {b_name}</blockquote>\n\n🌟 **Extracted By :** {CR}\n\n<blockquote>**[✨ Stream it for the best Viewing Experience!]({url})**</blockquote>'
              t_captions["cctest"] = f'——— ✦ {str(count).zfill(3)} ✦ ———\n\n<blockquote>**⋅ ─  🔖 {t_name}  ─ ⋅**</blockquote>\n\n**[📽] Title :** {v_name} [{res}] {EX}.mkv\n\n<blockquote>📚 Batch Name : {b_name}</blockquote>\n\n🌟 **Extracted By :** {CR}\n\n<blockquote>✨ Press the <b>Start Button</b> to Start the Test!</blockquote>'
              t_captions["ccyt"] = f'——— ✦ {str(count).zfill(3)} ✦ ———\n\n<blockquote>**⋅ ─  🔖 {t_name}  ─ ⋅**</blockquote>\n\n**[📽] Title :** {v_name} [{res}] {EX}.mkv\n\n<blockquote>📚 Batch Name : {b_name}</blockquote>\n\n🌟 **Extracted By :** {CR}\n\n<blockquote>**[🌟 It seems that this Video can be best enjoyed on YouTube.]({url})**</blockquote>'
              t_captions["cc1"] = f'——— ✦ {str(count).zfill(3)} ✦ ———\n\n<blockquote>**⋅ ─  🔖 {t_name}  ─ ⋅**</blockquote>\n\n**[📁] Title :** {v_name} {EX}.pdf\n\n<blockquote>📚 Batch Name : {b_name}</blockquote>\n\n🌟 **Extracted By :** {CR}'
              t_captions["cchtml"] = f'——— ✦ {str(count).zfill(3)} ✦ ———\n\n<blockquote>**⋅ ─  🔖 {t_name}  ─ ⋅**</blockquote>\n\n**[📁] Title :** {v_name} {EX}.html\n\n<blockquote>📚 Batch Name : {b_name}</blockquote>\n\n🌟 **Extracted By :** {CR}'
        elif caption_style == "style6":
              t_captions["cc"] = f'📋 **Title :** `{v_name}`\n🎞️ **Extension :** {EX}.mkv\n📏 **Resolution :** [{res}]\n\n<blockquote>📒 <b>Topic Name :</b> {t_name}\n📚 <b>Course Name :</b> {b_name}</blockquote>\n\n❖─────── **{CR}** ───────❖'
              t_captions["ccstream"] = f'📋 **Title :** `{v_name}`\n🎞️ **Extension :** {EX}.mkv\n📏 **Resolution :** [{res}]\n\n<blockquote>📒 <b>Topic Name :</b> {t_name}\n📚 <b>Course Name :</b> {b_name}</blockquote>\n\n❖──────── **{CR}** ────────❖\n\n<blockquote>**[✨ Stream it for the best Viewing Experience!]({url})**</blockquote>'
              t_captions["cctest"] = f'📋 **Title :** `{v_name}`\n🎞️ **Extension :** {EX}.mkv\n📏 **Resolution :** [{res}]\n\n<blockquote>📒 <b>Topic Name :</b> {t_name}\n📚 <b>Course Name :</b> {b_name}</blockquote>\n\n❖──────── **{CR}** ────────❖\n\n<blockquote>✨ Press the <b>Start Button</b> to Start the Test!</blockquote>'
              t_captions["ccyt"] = f'📋 **Title :** `{v_name}`\n🎞️ **Extension :** {EX}.mkv\n📏 **Resolution :** [{res}]\n\n<blockquote>📒 <b>Topic Name :</b> {t_name}\n📚 <b>Course Name :</b> {b_name}</blockquote>\n\n❖──────── **{CR}** ────────❖\n\n<blockquote>**[🌟 It seems that this Video can be best enjoyed on YouTube.]({url})**</blockquote>'
              t_captions["cc1"] = f'📋 **Title :** `{v_name}`\n🎞️ **Extension :** {EX}.pdf\n\n<blockquote>📒 <b>Topic Name :</b> {t_name}\n📚 <b>Course Name :</b> {b_name}</blockquote>\n\n❖──────── **{CR}** ────────❖'
              t_captions["cchtml"] = f'📋 **Title :** `{v_name}`\n🎞️ **Extension :** {EX}.html\n\n<blockquote>📒 <b>Topic Name :</b> {t_name}\n📚 <b>Course Name :</b> {b_name}</blockquote>\n\n❖──────── **{CR}** ────────❖'
        else:
              t_captions["cc"] = f'**——— ✦ {str(count).zfill(3)} ✦ ———**\n\n<blockquote>**⋅ ─  🔖 {t_name}  ─ ⋅**</blockquote>\n\n**🎞️ Title :** `{v_name}`\n├── **Extention** : {EX}.mkv\n├── **Resolution** : [{res}]\n\n<blockquote>**📚 Course :** {b_name}</blockquote>\n\n**🌟 Extracted By : {CR}**'
              t_captions["ccstream"] = f'**——— ✦ {str(count).zfill(3)} ✦ ———**\n\n<blockquote>**⋅ ─  🔖 {t_name}  ─ ⋅**</blockquote>\n\n**🎞️ Title :** `{v_name}`\n├── **Extention** : {EX}.mkv\n├── **Resolution** : [{res}]\n\n<blockquote>**📚 Course :** {b_name}</blockquote>\n\n**🌟 Extracted By : {CR}**\n\n<blockquote>**[✨ Stream it for the best Viewing Experience!]({url})**</blockquote>'
              t_captions["cctest"] = f'**——— ✦ {str(count).zfill(3)} ✦ ———**\n\n<blockquote>**⋅ ─  🔖 {t_name}  ─ ⋅**</blockquote>\n\n**🎞️ Title :** `{v_name}`\n├── **Extention** : {EX}.mkv\n├── **Resolution** : [{res}]\n\n<blockquote>**📚 Course :** {b_name}</blockquote>\n\n**🌟 Extracted By : {CR}**\n\n<blockquote>✨ Press the <b>Start Button</b> to Start the Test!</blockquote>'
              t_captions["ccyt"] = f'**——— ✦ {str(count).zfill(3)} ✦ ———**\n\n<blockquote>**⋅ ─  🔖 {t_name}  ─ ⋅**</blockquote>\n\n**🎞️ Title :** `{v_name}`\n├── **Extention** : {EX}.mkv\n├── **Resolution** : [{res}]\n\n<blockquote>**📚 Course :** {b_name}</blockquote>\n\n**🌟 Extracted By : {CR}**\n\n<blockquote>**[🌟 It seems that this Video can be best enjoyed on YouTube.]({url})**</blockquote>'
              t_captions["cc1"] = f'**——— ✦ {str(count).zfill(3)} ✦ ———**\n\n<blockquote>**⋅ ─  🔖 {t_name}  ─ ⋅**</blockquote>\n\n**📁 Title :** `{v_name}`\n├── **Extention** : {EX}.pdf \n\n<blockquote>**📚 Course :** {b_name}</blockquote>\n\n**🌟 Extracted By : {CR}**'
              t_captions["cchtml"] = f'**——— ✦ {str(count).zfill(3)} ✦ ———**\n\n<blockquote>**⋅ ─  🔖 {t_name}  ─ ⋅**</blockquote>\n\n**📁 Title :** `{v_name}`\n├── **Extention** : {EX}.html \n\n<blockquote>**📚 Course :** {b_name}</blockquote>\n\n**🌟 Extracted By : {CR}**'  
        
        
        return t_captions                 


def SendErrorMessage(count, e, title, url, CR):
      return f'''<blockquote>
╭━━━━━━━━━━━━━━━━➣
┣⪼ ❌ <b>Failed to Download</b>!
┣⪼ 📝 <b>Title : ({str(count).zfill(3)}).</b> `{title}`
┣⪼ 🔗 <b>URL :</b> [Click to View SourceUrl]({url})
┣⪼ ⚠️ <b>Error Details :</b>
┃     ╰─⪼ <i>{e}</i>
┣⪼ 💡 <b>Tip :</b> Contact {CR}
╰━━━━━━━━━━━━━━━━➣
</blockquote>'''